---
downloads: ~/.ansible-downloads/

configure_dotfiles: true
configure_terminal: true
configure_osx: true

# Set to 'true' to configure the Dock via dockutil.
configure_dock: true
dockitems_remove:
- Launchpad
- TV
- Podcasts
- Mail
- Maps
- Photos
- FaceTime
- Calendar
- Contacts
- Reminders
- Music
- News
dockitems_persist:
- name: "Safari"
   path: "/Applications/Safari.app/"
   pos: 2
- name: "Notes"
   path: "/Applications/Notes.app/"
   pos: 3
- name: "Messages"
   path: "/Applications/Messages.app/"
   pos: 4
- name: "Activity Monitor"
   path: "/System/Applications/Utilities/Activity Monitor.app/"
   pos: 5
- name: "Terminal"
   path: "/System/Applications/Utilities/Terminal.app"
   pos: 6
- name: "App Store"
   path: "/Applications/App Store.app"
   pos: 7
- name: "1Password 7"
   path: "/Applications/1Password 7.app/"
   pos: 8
- name: "Microsoft Remote Desktop"
   path: "/Applications/Microsoft Remote Desktop.app"
   pos: 9
- name: "Parallels Desktop"
   path: "/Applications/Parallels Desktop.app"
   pos: 10
- name: "Google Chrome"
   path: "/Applications/Google Chrome.app"
   pos: 11

configure_sudoers: false
sudoers_custom_config: ''
# Example:
# sudoers_custom_config: |
#   # Allow users in admin group to use sudo with no password.
#   %admin ALL=(ALL) NOPASSWD: ALL

dotfiles_repo: https://github.com/northportio/dotfiles.git
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: ~/Development/GitHub/dotfiles
dotfiles_files:
  - .zshrc
  - .gitignore
  - .inputrc
  - .osx
  - .vimrc

homebrew_installed_packages:
  # - ansible # Installed via Pip.
  - curl
  - dialog
  - htop
  - iperf3
  - netcat
  - openssh
  - neofetch
  - bash-completion
  - git
  - github/gh/gh
  - gpg
  - iperf
  - nmap
  - node
  - php
  - ssh-copy-id
  - openssl
  - pv
  - wget
  - zsh-history-substring-search
  - speedtest-cli
  - proxychains-ng

homebrew_taps:
  - homebrew/core
  - homebrew/cask

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - docker
  - firefox
  - google-chrome
  - setapp
  - slack
  - 1password
  - tunnelblick
  - openvpn-connect
  - parallels
  - zerotier-one
  - aerial
  - macdown
  - tor-browser
  - x2goclient
  - balenaetcher
  - cyberduck
  - suspicious-package
  - vlc
  - signal
  - raspberry-pi-imager
  - alfred
  - arduino
  - cheatsheet
  - iina
  - paragon-extfs
  - paragon-ntfs
  - visual-studio-code
  - vip-access
  - wireshark


# See `geerlingguy.mac.mas` role documentation for usage instructions.
mas_installed_apps:
  - { id: 412946682, name: "SubnetCalc (2.1)" }
  - { id: 462058435, name: "Microsoft Excel (16.51)" }
  - { id: 1153157709, name: "Speedtest (1.20)" }
  - { id: 1475387142, name: "Tailscale (1.10.1)" }
  - { id: 462054704, name: "Microsoft Word (16.51)" }
  - { id: 836847379, name: "NET_Toolkit (2.1.11)" }
  - { id: 424389933, name: "Final Cut Pro (10.5.4)" }
  - { id: 1037126344, name: "Apple Configurator 2 (2.14)" }
  - { id: 462062816, name: "Microsoft PowerPoint (16.51)" }
  - { id: 434290957, name: "Motion (5.5.3)" }
  - { id: 494803304, name: "WiFi Explorer (3.3)" }
  - { id: 1295203466, name: "Microsoft Remote Desktop (10.6.7)" }
  - { id: 1497506650, name: "Yubico Authenticator (5.0.5)" }
  - { id: 424390742, name: "Compressor (4.5.4)" }
  - { id: 1451685025, name: "WireGuard (1.0.13)" }
  - { id: 985367838, name: "Microsoft Outlook (16.51)" }
  - { id: 1381004916, name: "Discovery (2.0.3)" }
  - { id: 877615577, name: "Serial (1.4.10)" }
  - { id: 1157491961, name: "PLIST Editor (1.31)" }
mas_email: ""
mas_password: ""

osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
# - name: drush
#   state: present # present/absent, default: present
#   version: "^8.1" # default: N/A
gem_packages: []
# - name: bundler
#   state: present # present/absent/latest, default: present
#   version: "~> 1.15.1" # default: N/A
npm_packages: []
# - name: webpack
#   state: present # present/absent/latest, default: present
#   version: "^2.6" # default: N/A
pip_packages: []
# - name: mkdocs
#   state: present # present/absent/latest, default: present
#   version: "0.16.3" # default: N/A

# Set to 'true' to configure Sublime Text.
configure_sublime: false
sublime_base_path: '~/Library/Application Support/Sublime Text'
sublime_config_path: "Packages/User"
sublime_package_control:
  - "DocBlockr"
  - "Dockerfile Syntax Highlighting"
  - "FileDiffs"
  - "GitHub Flavored Markdown Preview"
  - "Jinja2"
  - "Package Control"
  - "PHP-Twig"
  - "Pretty JSON"
  - "SublimeLinter"
  - "SublimeLinter-contrib-yamllint"
  - "TrailingSpaces"
  - "WordCount"

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
